### ISSUE TITLE
kotlinx.serialization.SerializationException: Serializer for class 'Object' is not found

### ISSUE THREAD

**Issue by MhuiHugh** [catchpig/kmvvm#11]
@POST(“xxxx”)
suspend fun postInfo(@Body body: @JvmSuppressWildcards Map<String, Any?>): String?
博客解决方式未解决  https://blog.csdn.net/wangxiaocheng16/article/details/103961457

**Comment by MhuiHugh** [comment]
![报错](https://user-images.githubusercontent.com/12462349/233946876-30e7e646-e61b-49e9-b590-0f3a159ee10d.PNG)

**Comment by catchpig** [comment]
> ![报错](https://user-images.githubusercontent.com/12462349/233946876-30e7e646-e61b-49e9-b590-0f3a159ee10d.PNG)

把你的Map数据发出来看一下

gradle是否配置kotlin的序列化插件?

**Comment by MhuiHugh** [comment]
正常数据id是Int用了Any 上面报错 map: MutableMap<String, Any?>    {"id":3,,"name":"姓名123"}
非正常数据id转成String 上面报错 map: MutableMap<String, String?>    {"id":"3",,"name":"姓名123"}
定义一个data class Req不用MutableMap可解决只是麻烦点
    //retrofit2 
    @POST("save/info")
    suspend fun userSave(@Body body: Map<String, Any?>): String?
