### ISSUE TITLE
混淆规则要怎么写？

### ISSUE THREAD

**Issue by WhoIsAA** [catchpig/kmvvm#2]
RT

**Comment by catchpig** [comment]
暂时没有加混淆，你那边需要混淆嘛？

**Comment by WhoIsAA** [comment]
谢谢，来信已收到，我会尽快回复你..

**Comment by WhoIsAA** [comment]
是啊，加上混淆后就崩溃了，提示@Adapter注解报错之类的

**Comment by catchpig** [comment]
你把所有框架里面的注解都忽略掉吧，因为注解混淆了，注解会不生效的，我后面更新一下框架的混淆

**Comment by WhoIsAA** [comment]
好的，谢谢～

**Comment by catchpig** [comment]
混淆已经加上了,请看文档,你适配一下,看程序是否能正常运行?

**Comment by WhoIsAA** [comment]
可以了

**Comment by MhuiHugh** [comment]
-dontwarn com.catchpig.mvvm**
-keep class com.catchpig.mvvm** { *; }

**Comment by WhoIsAA** [comment]
谢谢，来信已收到，我会尽快回复你..
