### ISSUE TITLE
啥时候升级gradle 7.2

### ISSUE THREAD

**Issue by marren06** [catchpig/kmvvm#3]
你好作者：

1.新建项目默认都是最新的gradle,按照集成步骤报错，gradle 升级导致引入插件的方式改变，请问什么时候能升级最新版本的gradle
2.请问下自定义ResponseBodyConverter 是不是得要重写BaseResponseBodyConverter？ 因为返回的数据格式格式各样
目前情况下处理是不是要绑定SerializationResponseBodyConverter拿到全部Response处理？

3.有没有沟通群？想讨论学习下

**Comment by catchpig** [comment]
1.新建项目默认都是最新的gradle,按照集成步骤报错，gradle 升级导致引入插件的方式改变，请问什么时候能升级最新版本的gradle
**我这边升级7.2是没有报错的,如果有错误请贴出错误的日志**
2.请问下自定义ResponseBodyConverter 是不是得要重写BaseResponseBodyConverter？ 因为返回的数据格式格式各样
目前情况下处理是不是要绑定SerializationResponseBodyConverter拿到全部Response处理？
**你如果需要自定义返回数据格式,那就需要重写BaseResponseBodyConverter**

3.有没有沟通群？想讨论学习下
**暂时还没有沟通群,主要star数还比较少,建群没有太大的必要,如果有什么问题可以直接给我提issue,我会尽快解决的**

**Comment by catchpig** [comment]
请问你的问题解决了吗?

**Comment by marren06** [comment]
> 请问你的问题解决了吗?
我重新复制你的工程gradle文件后可以了。
我可能是用最新gradle7.2新建的工程，gradle引入方式变了，导致我有困惑还以为是gradle的问题。
感谢！！
