### ISSUE TITLE
handlerErrorCode只能抛出异常吗？

### ISSUE THREAD

**Issue by WhoIsAA** [catchpig/kmvvm#4]
试了下demo中的login方法，填错了账号和密码后，会直接抛出空指针或者其他异常，如果想处理这次登录失败，要怎么改吗？

**Comment by catchpig** [comment]
> 试了下demo中的login方法，填错了账号和密码后，会直接抛出空指针或者其他异常，如果想处理这次登录失败，要怎么改吗？

你根据返回的code码定义不同的异常,
再到你对应的activity或者fragment中flow(协程)中catch这个异常,去做处理.
也可以实现IFlowError接口,仿造demo中的MessageFlowError,统一处理异常,这种方式你需要在activity或者fragment中调用BaseVMActivity和BaseVMFragment中lifecycleFlow*****封装的方法

可以加入QQ群,我帮你解答

**Comment by WhoIsAA** [comment]
谢谢，来信已收到，我会尽快回复你..
