### ISSUE TITLE
出现“Incompatible types: SerializationResponseBodyConverter and ResponseBodyConverter?”的错误

### ISSUE THREAD

**Issue by guozhenguang** [catchpig/kmvvm#7]
在整个项目当中，如果只使用SerializationResponseBodyConverter 或者 只使用ResponseBodyConverter时，在ksp生成代码时，就会报这个错误。

**Comment by catchpig** [comment]
[it is fixed](https://github.com/catchpig/kmvvm/commit/2400fc7ce0598d2be3eb6b6e497f2526ef16282f)
